defaults:
  - _self_
  - model: mbgcn
  - dataset: yambda
  - dataloader: link_neighbor
  - optimizer: adam
  - loss: bpr
  - trainer: default
  - logger: comet
  - metrics: default

seed: 42
device: "cuda"
debug: False

experiment_name: "mbgcn-yambda"
