defaults:
  - _self_
  - dataset: yambda
  - model: mbgcn
  - dataloader: link_neighbor
  - optimizer: adam
  - loss: bpr
  - trainer: default
  - metrics: default
  - logger: clearml

seed: 42
device: "cuda"
experiment_name: "mbgcn-yambda-base"
debug: False

hydra:
  run:
    dir: outputs/${experiment_name}/${now:%Y-%m-%d}/${now:%H-%M-%S}