# src/configs/eval/eval.yaml
defaults:
  - _self_
  - /model: mbgcn          # Load model config so we can access ${model.*}
  - /recommender: mbgcn    # Load the recommender wrapper we just created
  - /dataset: yambda

clearml:
  project_name: "Yambda-RecSys"
  tags: ["evaluation", "mbgcn"]

metrics:
  k: 20

dataset:
  processed_dir: "data/processed"