defaults:
  - _self_
  - /model: mbgcn
  - /dataset: yambda

recommender_name: "ItemKNN"
model_path: "outputs/2025-11-25/21-19-01/checkpoints/best_model.pth"
item_features_path: "src/datasets/embeddings.parquet"
device: "mps"
max_test_samples: 10

clearml:
  project_name: "Yambda-RecSys"
  tags: ["evaluation", "mbgcn"]

metrics:
  k: 20

dataset:
  processed_dir: "data/processed"
