root_dir: "./data"
train_file: "src/datasets/multi_event_train.parquet"
val_file: "src/datasets/multi_event_val.parquet"
test_file: "src/datasets/multi_event_test.parquet"

# items' semantic embeddings
item_features_path: null